name: Run-Tests

on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt


      - name: Run tests
        run: ./run_tests

  run-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup Operator Environment
      uses: charmed-kubernetes/actions-operator@master
      with:
        provider: microk8s

    - name: Install Dependencies
      run: python -m pip install -r requirements-dev.txt

    - name: Build
      run: |
        charmcraft build

    - name: Test
      run: python -m pytest integration.py
